create table achievements (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(255) not null,
    icon varchar(255) not null,
    unlocked boolean not null,
    progress integer,
    total integer
);

create table chat_messages (
    id bigint generated by default as identity primary key,
    sender varchar(255) not null,
    collective_code varchar(255),
    text varchar(1500) not null,
    image_data text,
    image_mime_type varchar(120),
    image_file_name varchar(255),
    reply_to_message_id bigint,
    timestamp timestamp(6) not null,
    reactions text not null default '{}',
    poll text
);

create table collectives (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    join_code varchar(255) not null,
    owner_member_id bigint not null,
    monthly_prize text,
    pant_goal integer
);

create unique index uq_collectives_join_code on collectives (join_code);

create table collective_enabled_achievements (
    collective_id bigint not null,
    achievement_key varchar(50) not null,
    primary key (collective_id, achievement_key)
);

create table events (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    collective_code varchar(255),
    date date not null,
    time time(6) not null,
    end_time time(6),
    type varchar(255) not null,
    organizer varchar(255) not null,
    attendees integer not null,
    description varchar(255),
    google_event_id varchar(255)
);

create table expenses (
    id bigint generated by default as identity primary key,
    description varchar(255) not null,
    amount integer not null,
    paid_by varchar(255) not null,
    collective_code varchar(255),
    category varchar(255) not null,
    date date not null,
    deadline_date date
);

create table expense_participants (
    expense_id bigint not null,
    member_name varchar(255) not null
);

create table invitations (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    collective_code varchar(255) not null,
    invited_by varchar(255) not null,
    created_at timestamp(6) not null,
    accepted boolean not null,
    accepted_at timestamp(6)
);

create table members (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    password_hash varchar(255),
    level integer not null,
    xp integer not null,
    collective_code varchar(255),
    status varchar(255) not null,
    chemistry text,
    preferences text,
    assignment_history text,
    google_access_token text,
    google_refresh_token varchar(512),
    notification_preferences text
);

create unique index uq_members_name on members (name);
alter table members add constraint uq_members_email unique (email);

create table notifications (
    id bigint generated by default as identity primary key,
    user_name varchar(255) not null,
    message text not null,
    type varchar(64) not null default 'TASK_ASSIGNED',
    timestamp timestamp(6) with time zone not null default now(),
    read boolean not null default false
);

create table pant_entries (
    id bigint generated by default as identity primary key,
    bottles integer not null,
    amount integer not null,
    added_by varchar(255) not null,
    collective_code varchar(255),
    date date not null
);

create table personal_settlements (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    paid_by varchar(255) not null,
    paid_to varchar(255) not null,
    amount integer not null,
    created_at timestamp(6) not null default now()
);

create table rooms (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    minutes integer not null,
    collective_id bigint
);

create table settlement_checkpoints (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    settled_by varchar(255) not null,
    last_expense_id bigint not null,
    created_at timestamp(6) not null
);

create table shopping_items (
    id bigint generated by default as identity primary key,
    item varchar(255) not null,
    added_by varchar(255) not null,
    collective_code varchar(255),
    completed boolean not null,
    completed_at timestamp(6)
);

create table tasks (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    assignee varchar(255) not null,
    collective_code varchar(255),
    due_date date not null,
    category varchar(255) not null,
    completed boolean not null,
    xp_awarded boolean not null,
    completed_by varchar(255),
    completed_at timestamp(6),
    xp integer not null,
    penalty_xp integer not null default 0,
    recurrence_rule varchar(128),
    recurring boolean not null,
    assignment_reason varchar(512),
    assignment_feedback text,
    assignment_score varchar(512),
    constraint tasks_category_check check (
        category in (
            'CLEANING',
            'VACUUMING',
            'MOPPING',
            'BATHROOM',
            'KITCHEN',
            'LAUNDRY',
            'DISHES',
            'TRASH',
            'DUSTING',
            'WINDOWS',
            'SHOPPING',
            'OTHER'
        )
    )
);

create table task_feedback (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    author varchar(255) not null,
    message text not null,
    anonymous boolean not null default false,
    image_data text,
    image_mime_type varchar(120),
    created_at timestamp(6) not null
);

alter table collective_enabled_achievements
    add constraint fk_collective_enabled_achievements_collective
    foreign key (collective_id) references collectives (id) on delete cascade;

alter table expense_participants
    add constraint fk_expense_participants_expense
    foreign key (expense_id) references expenses (id);

alter table rooms
    add constraint fk_rooms_collective
    foreign key (collective_id) references collectives (id);

alter table task_feedback
    add constraint fk_task_feedback_task
    foreign key (task_id) references tasks (id) on delete cascade;
